export default [
  {
    id: 1,
    img: ".../../../../../public/assets/images/mock-img.png",
    city: "Tashkent",
    view: 1220,
    likes: true,
    body: "Olmazor tumanida joylashgan2x kvartira ijaraga beriladi",
    price: "2250000",
  },
  {
    id: 2,
    img: ".../../../../../public/assets/images/mock-img.png",
    city: "Tashkent",
    view: 120,
    likes: true,
    body: "Olmazor tumanida joylashgan2x kvartira ijaraga beriladi",
    price: "2250000",
  },
  {
    id: 3,
    img: ".../../../../../public/assets/images/mock-img.png",
    city: "Tashkent",
    view: 120,
    likes: false,
    body: "Olmazor tumanida joylashgan2x kvartira ijaraga beriladi",
    price: "2250000",
  },
  {
    id: 4,
    img: ".../../../../../public/assets/images/mock-img.png",
    city: "Tashkent",
    view: 120,
    likes: false,
    body: "Olmazor tumanida joylashgan2x kvartira ijaraga beriladi",
    price: "2250000",
  },
  {
    id: 5,
    img: ".../../../../../public/assets/images/mock-img.png",
    city: "Tashkent",
    view: 120,
    likes: false,
    body: "Olmazor tumanida joylashgan2x kvartira ijaraga beriladi",
    price: "2250000",
  },
  {
    id: 6,
    img: ".../../../../../public/assets/images/mock-img.png",
    city: "Tashkent",
    view: 120,
    likes: false,
    body: "Olmazor tumanida joylashgan2x kvartira ijaraga beriladi",
    price: "2250000",
  },
  {
    id: 7,
    img: ".../../../../../public/assets/images/mock-img.png",
    city: "Tashkent",
    view: 120,
    likes: true,
    body: "Olmazor tumanida joylashgan2x kvartira ijaraga beriladi",
    price: "2250000",
  },

  {
    id: 9,
    img: ".../../../../../public/assets/images/mock-img.png",
    city: "Tashkent",
    view: 120,
    likes: true,
    body: "Olmazor tumanida joylashgan2x kvartira ijaraga beriladi",
    price: "2250000",
  },
  {
    id: 10,
    img: ".../../../../../public/assets/images/mock-img.png",
    city: "Tashkent",
    view: 1220,
    likes: false,
    body: "Olmazor tumanida joylashgan2x kvartira ijaraga beriladi",
    price: "2250000",
  },
  {
    id: 10,
    img: ".../../../../../public/assets/images/mock-img.png",
    city: "Tashkent",
    view: 1220,
    likes: false,
    body: "Olmazor tumanida joylashgan2x kvartira ijaraga beriladi",
    price: "2250000",
  },
]
